### ISSUE TITLE
template_functions.go : error in mapping

### ISSUE THREAD

**Issue by apatrikis** [CausticLab/go-rancher-gen#13]
The file "template_functions.go" has an error in mapping the function "whereLabelMatches".
It points to "whereLabelEquals".

		"whereLabelEquals":  whereLabelEquals,
		"whereLabelMatches": whereLabelEquals,

Sorry for not providing a fork/fix for this.

**Comment by Munsio** [comment]
Hi @apatrikis thanks for raising this issue but i have to admit that this repository is deprecated and not actively maintained anymore.
I will update the Readme to indicate this.

Sorry that i couldn't help you
